theme: jekyll-theme-cayman
title: <a href="http://www.zina-studio.com/">
         <img src="https://raw.githubusercontent.com/AugustoGarcia/Coronasurveys-web/master/assets/logo.jpg" 
         height="100" width="200">
      </a> <br> 
      <font size="-5">CoronaSurveys</font>
description: Monitoring the Incidence of COVID-19 via Open Polls 
         <br> <br> 
         The following results present our estimations on the incidence of COVID-19 in the countries from which we have enough information. 
         You can help by regularly completing the survey below.
github:
  is_project_page: false
